/**
 * Seed dictionary for shopping-list autocomplete: 500 common food items,
 * 5 per line. Loaded once into the `dictionary` table on first launch;
 * after that the table is the source of truth (users add/edit/delete).
 */
export const SEED_FOOD_ITEMS: string[] = [
  // Vegetables (62)
  'Carrots', 'Cabbage', 'Cauliflower', 'Broccoli', 'Spinach',
  'Lettuce', 'Romaine Lettuce', 'Iceberg Lettuce', 'Kale', 'Arugula',
  'Swiss Chard', 'Collard Greens', 'Brussels Sprouts', 'Asparagus', 'Green Beans',
  'Peas', 'Snow Peas', 'Snap Peas', 'Celery', 'Cucumber',
  'Zucchini', 'Yellow Squash', 'Butternut Squash', 'Pumpkin', 'Eggplant',
  'Bell Pepper', 'Red Bell Pepper', 'Green Bell Pepper', 'Jalapeno', 'Poblano Pepper',
  'Onion', 'Red Onion', 'Yellow Onion', 'Green Onions', 'Shallots',
  'Leeks', 'Garlic', 'Ginger', 'Potatoes', 'Red Potatoes',
  'Russet Potatoes', 'Sweet Potatoes', 'Yams', 'Turnips', 'Parsnips',
  'Rutabaga', 'Beets', 'Radishes', 'Tomatoes', 'Cherry Tomatoes',
  'Grape Tomatoes', 'Roma Tomatoes', 'Corn', 'Corn on the Cob', 'Mushrooms',
  'Portobello Mushrooms', 'Shiitake Mushrooms', 'Artichokes', 'Okra', 'Fennel',
  'Bok Choy', 'Red Cabbage',
  // Fruits (53)
  'Apples', 'Gala Apples', 'Fuji Apples', 'Granny Smith Apples', 'Honeycrisp Apples',
  'Bananas', 'Oranges', 'Clementines', 'Tangerines', 'Grapefruit',
  'Lemons', 'Limes', 'Grapes', 'Red Grapes', 'Green Grapes',
  'Strawberries', 'Blueberries', 'Raspberries', 'Blackberries', 'Cranberries',
  'Cherries', 'Peaches', 'Nectarines', 'Plums', 'Apricots',
  'Pears', 'Asian Pears', 'Mangoes', 'Pineapple', 'Watermelon',
  'Cantaloupe', 'Honeydew Melon', 'Kiwi', 'Papaya', 'Guava',
  'Pomegranate', 'Figs', 'Dates', 'Raisins', 'Prunes',
  'Dried Cranberries', 'Dried Apricots', 'Avocados', 'Coconut', 'Dragon Fruit',
  'Passion Fruit', 'Lychee', 'Persimmons', 'Rhubarb', 'Plantains',
  'Applesauce', 'Mandarin Oranges', 'Key Limes',
  // Meat & Poultry (38)
  'Chicken Breast', 'Chicken Thighs', 'Chicken Wings', 'Chicken Drumsticks', 'Whole Chicken',
  'Ground Chicken', 'Ground Beef', 'Ground Turkey', 'Ground Pork', 'Turkey Breast',
  'Ribeye Steak', 'Sirloin Steak', 'Filet Mignon', 'Flank Steak', 'Skirt Steak',
  'Chuck Roast', 'Brisket', 'Beef Ribs', 'Stew Meat', 'Pork Chops',
  'Pork Tenderloin', 'Pork Shoulder', 'Pork Ribs', 'Ham', 'Bacon',
  'Turkey Bacon', 'Sausage', 'Italian Sausage', 'Breakfast Sausage', 'Bratwurst',
  'Chorizo', 'Hot Dogs', 'Deli Ham', 'Deli Turkey', 'Roast Beef',
  'Salami', 'Pepperoni', 'Lamb Chops',
  // Seafood (22)
  'Salmon', 'Smoked Salmon', 'Canned Salmon', 'Tuna', 'Canned Tuna',
  'Tilapia', 'Cod', 'Halibut', 'Trout', 'Catfish',
  'Sardines', 'Anchovies', 'Shrimp', 'Crab', 'Lobster',
  'Scallops', 'Mussels', 'Clams', 'Oysters', 'Fish Sticks',
  'Crab Cakes', 'Imitation Crab',
  // Dairy & Eggs (39)
  'Milk', 'Whole Milk', 'Skim Milk', 'Almond Milk', 'Oat Milk',
  'Soy Milk', 'Coconut Milk', 'Heavy Cream', 'Half and Half', 'Buttermilk',
  'Condensed Milk', 'Evaporated Milk', 'Butter', 'Unsalted Butter', 'Margarine',
  'Eggs', 'Egg Whites', 'Cheddar Cheese', 'Mozzarella Cheese', 'Parmesan Cheese',
  'Swiss Cheese', 'Provolone Cheese', 'American Cheese', 'Feta Cheese', 'Goat Cheese',
  'Blue Cheese', 'Brie', 'Gouda', 'Monterey Jack Cheese', 'Pepper Jack Cheese',
  'Ricotta Cheese', 'Cottage Cheese', 'Cream Cheese', 'Shredded Cheese', 'Yogurt',
  'Greek Yogurt', 'Sour Cream', 'Whipped Cream', 'Ice Cream',
  // Bakery (27)
  'Bread', 'White Bread', 'Wheat Bread', 'Sourdough Bread', 'Rye Bread',
  'Multigrain Bread', 'French Bread', 'Baguette', 'Pita Bread', 'Naan',
  'Flour Tortillas', 'Corn Tortillas', 'Bagels', 'English Muffins', 'Croissants',
  'Dinner Rolls', 'Hamburger Buns', 'Hot Dog Buns', 'Muffins', 'Donuts',
  'Cinnamon Rolls', 'Biscuits', 'Cornbread', 'Breadcrumbs', 'Pie Crust',
  'Pizza Dough', 'Cookies',
  // Grains & Pasta (40)
  'Rice', 'White Rice', 'Brown Rice', 'Jasmine Rice', 'Basmati Rice',
  'Wild Rice', 'Rice Noodles', 'Quinoa', 'Couscous', 'Barley',
  'Oats', 'Oatmeal', 'Rolled Oats', 'Steel Cut Oats', 'Granola',
  'Cereal', 'Corn Flakes', 'Pasta', 'Spaghetti', 'Penne',
  'Fettuccine', 'Linguine', 'Macaroni', 'Rigatoni', 'Rotini',
  'Angel Hair Pasta', 'Lasagna Noodles', 'Egg Noodles', 'Ramen Noodles', 'Orzo',
  'Gnocchi', 'Tortellini', 'Ravioli', 'Flour', 'All-Purpose Flour',
  'Whole Wheat Flour', 'Bread Flour', 'Almond Flour', 'Cornmeal', 'Cornstarch',
  // Canned & Jarred (38)
  'Canned Corn', 'Canned Green Beans', 'Canned Tomatoes', 'Diced Tomatoes', 'Crushed Tomatoes',
  'Tomato Paste', 'Tomato Sauce', 'Marinara Sauce', 'Pasta Sauce', 'Alfredo Sauce',
  'Pesto', 'Salsa', 'Black Beans', 'Kidney Beans', 'Pinto Beans',
  'Navy Beans', 'Garbanzo Beans', 'Cannellini Beans', 'Refried Beans', 'Baked Beans',
  'Lima Beans', 'Lentils', 'Split Peas', 'Canned Chicken', 'Chicken Broth',
  'Beef Broth', 'Vegetable Broth', 'Chicken Noodle Soup', 'Tomato Soup', 'Cream of Mushroom Soup',
  'Chili', 'Canned Pumpkin', 'Olives', 'Green Olives', 'Black Olives',
  'Pickles', 'Relish', 'Sauerkraut',
  // Condiments & Oils (39)
  'Ketchup', 'Mustard', 'Dijon Mustard', 'Honey Mustard', 'Mayonnaise',
  'Ranch Dressing', 'Italian Dressing', 'Caesar Dressing', 'Salad Dressing', 'BBQ Sauce',
  'Hot Sauce', 'Sriracha', 'Buffalo Sauce', 'Soy Sauce', 'Teriyaki Sauce',
  'Worcestershire Sauce', 'Fish Sauce', 'Oyster Sauce', 'Hoisin Sauce', 'Tartar Sauce',
  'Horseradish', 'Guacamole', 'Hummus', 'Tahini', 'Olive Oil',
  'Vegetable Oil', 'Canola Oil', 'Coconut Oil', 'Sesame Oil', 'Avocado Oil',
  'Cooking Spray', 'White Vinegar', 'Apple Cider Vinegar', 'Balsamic Vinegar', 'Red Wine Vinegar',
  'Rice Vinegar', 'Gravy', 'Steak Sauce', 'Enchilada Sauce',
  // Spices & Herbs (35)
  'Salt', 'Sea Salt', 'Kosher Salt', 'Black Pepper', 'Garlic Powder',
  'Onion Powder', 'Paprika', 'Smoked Paprika', 'Chili Powder', 'Cayenne Pepper',
  'Red Pepper Flakes', 'Cumin', 'Coriander', 'Turmeric', 'Curry Powder',
  'Oregano', 'Basil', 'Fresh Basil', 'Thyme', 'Rosemary',
  'Sage', 'Parsley', 'Cilantro', 'Dill', 'Mint',
  'Chives', 'Bay Leaves', 'Cinnamon', 'Nutmeg', 'Cloves',
  'Italian Seasoning', 'Taco Seasoning', 'Lemon Pepper', 'Vanilla Extract', 'Sesame Seeds',
  // Baking & Spreads (20)
  'Sugar', 'Brown Sugar', 'Powdered Sugar', 'Honey', 'Maple Syrup',
  'Molasses', 'Baking Powder', 'Baking Soda', 'Yeast', 'Chocolate Chips',
  'Cocoa Powder', 'Pancake Mix', 'Cake Mix', 'Brownie Mix', 'Frosting',
  'Peanut Butter', 'Almond Butter', 'Nutella', 'Strawberry Jam', 'Grape Jelly',
  // Snacks (33)
  'Potato Chips', 'Tortilla Chips', 'Corn Chips', 'Pita Chips', 'Pretzels',
  'Popcorn', 'Microwave Popcorn', 'Crackers', 'Saltine Crackers', 'Graham Crackers',
  'Cheese Crackers', 'Rice Cakes', 'Trail Mix', 'Mixed Nuts', 'Peanuts',
  'Almonds', 'Cashews', 'Walnuts', 'Pecans', 'Pistachios',
  'Sunflower Seeds', 'Pumpkin Seeds', 'Chia Seeds', 'Flax Seeds', 'Granola Bars',
  'Protein Bars', 'Fruit Snacks', 'Beef Jerky', 'Chocolate', 'Dark Chocolate',
  'Candy', 'Gummy Bears', 'Marshmallows',
  // Beverages (25)
  'Water', 'Bottled Water', 'Sparkling Water', 'Soda', 'Cola',
  'Root Beer', 'Ginger Ale', 'Lemonade', 'Iced Tea', 'Orange Juice',
  'Grape Juice', 'Cranberry Juice', 'Pineapple Juice', 'Lemon Juice', 'Lime Juice',
  'Coffee', 'Ground Coffee', 'Instant Coffee', 'Tea', 'Green Tea',
  'Black Tea', 'Herbal Tea', 'Hot Chocolate', 'Chocolate Milk', 'Coconut Water',
  // Frozen (16)
  'Frozen Pizza', 'Frozen Vegetables', 'Frozen Broccoli', 'Frozen Spinach', 'Frozen Peas',
  'Frozen Corn', 'Frozen Fruit', 'Frozen Strawberries', 'Frozen Blueberries', 'French Fries',
  'Tater Tots', 'Hash Browns', 'Frozen Waffles', 'Chicken Nuggets', 'Frozen Burritos',
  'Frozen Lasagna',
  // Other (13)
  'Tofu', 'Tempeh', 'Veggie Burgers', 'Rotisserie Chicken', 'Protein Powder',
  'Miso Paste', 'Kimchi', 'Nori', 'Coconut Flakes', 'Panko Breadcrumbs',
  'Capers', 'Sun-Dried Tomatoes', 'Artichoke Hearts',
];
